name: CI/CD Pipeline

on:
  push:
    branches:
      - 'feature/**'
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run automated tests
      - name: Run automated tests
        run: npm test
        
      # 5️⃣ Lint HTML
      - name: Lint HTML
        run: npx html-validate --ext .html . 
        
      # 6️⃣ Lint CSS
      - name: Lint CSS
        run: npx stylelint "**/*.css"
        
      # 7️⃣ Lint JavaScript
      - name: Lint JavaScript
        run: npx eslint .
      
      # 8️⃣ Build application
      - name: Build application
        run: npm run build

      # 9️⃣ Build Docker image
      - name: Build Docker image
        run: |
          IMAGE_NAME=my-game-app
          IMAGE_TAG=${GITHUB_SHA::8}
          REPO=pranjalmohite21/task-game   # all lowercase!
          docker build -t "$IMAGE_NAME:$IMAGE_TAG" .
          docker tag "$IMAGE_NAME:$IMAGE_TAG" "ghcr.io/$REPO:$IMAGE_TAG"

      # 🔟 Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 1️⃣1️⃣ Push Docker image
      - name: Push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          REPO=pranjalmohite21/task-game
          docker push "ghcr.io/$REPO:$IMAGE_TAG"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: your-gcp-project-id

      - name: Deploy to Cloud Run
        run: |
          IMAGE_TAG=${GITHUB_SHA::8}
          IMAGE_NAME=ghcr.io/pranjalmohite21/task-game:$IMAGE_TAG
          gcloud run deploy my-game-app \
            --image "$IMAGE_NAME" \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
